//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellProducts.Model.Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTION
    {
        public int id { get; set; }
        public string idref { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string detail { get; set; }
        public string manager { get; set; }
    
        public virtual MANAGER MANAGER1 { get; set; }
    }
}
