//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellProducts.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CART
    {
        public int idorder { get; set; }
        public int idproduct { get; set; }
        public int amount { get; set; }
        public int price { get; set; }
    
        public virtual ORDER ORDER1 { get; set; }
        public virtual PRODUCT PRODUCT1 { get; set; }
    }
}
