//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellProducts.Model.Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORy
    {
        public CATEGORy()
        {
            this.CATEGORIES1 = new HashSet<CATEGORy>();
            this.PRODUCTS = new HashSet<PRODUCT>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> cat_parent { get; set; }
        public string detail { get; set; }
    
        public virtual ICollection<CATEGORy> CATEGORIES1 { get; set; }
        public virtual CATEGORy CATEGORy1 { get; set; }
        public virtual ICollection<PRODUCT> PRODUCTS { get; set; }
    }
}
