//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellProducts.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public CUSTOMER()
        {
            this.ORDERS = null;
        }
    
        public string phone { get; set; }
        public string name { get; set; }
        public string address { get; set; }
    
        public virtual IList<ORDER> ORDERS { get; set; }

        public override bool Equals(object obj)
        {
            return obj is CUSTOMER c &&
                   phone == c.phone &&
                   name == c.name &&
                   address == c.address &&
                   EqualityComparer<IList<ORDER>>.Default.Equals(ORDERS, c.ORDERS);
        }

        public override int GetHashCode()
        {
            int hashCode = 878048308;
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(phone);
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(name);
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(address);
            hashCode = hashCode * -1521134295 + EqualityComparer<IList<ORDER>>.Default.GetHashCode(ORDERS);
            return hashCode;
        }
    }
}
