//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellProducts.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORY
    {
        public int idorder { get; set; }
        public System.DateTime datetime { get; set; }
        public string detail { get; set; }
        public string act { get; set; }
    
        public virtual ORDER ORDER1 { get; set; }
    }
}
