//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellProducts.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MADEIN
    {
        public MADEIN()
        {
            this.PRODUCTS = null;
        }
    
        public int id { get; set; }
        public string location { get; set; }
        public string detail { get; set; }
    
        public virtual IList<PRODUCT> PRODUCTS { get; set; }

        public override bool Equals(object obj)
        {
            return obj is MADEIN m &&
                   id == m.id &&
                   location == m.location &&
                   detail == m.detail &&
                   EqualityComparer<IList<PRODUCT>>.Default.Equals(PRODUCTS, m.PRODUCTS);
        }

        public override int GetHashCode()
        {
            int hashCode = 5459751;
            hashCode = hashCode * -1521134295 + id.GetHashCode();
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(location);
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(detail);
            hashCode = hashCode * -1521134295 + EqualityComparer<IList<PRODUCT>>.Default.GetHashCode(PRODUCTS);
            return hashCode;
        }
    }
}
