//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellProducts.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANAGER
    {
        public MANAGER()
        {
            this.ACTIONS = new List<ACTION>();
            this.SETTINGS = new List<SETTING>();
        }
    
        public string account { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string type { get; set; }
        public Nullable<bool> is_disable { get; set; }
        public string comment { get; set; }
    
        public virtual IList<ACTION> ACTIONS { get; set; }
        public virtual IList<SETTING> SETTINGS { get; set; }
    }
}
