//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellProducts.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public ORDER()
        {
            this.CARTS = null;
            this.HISTORIES = null;
            this.CUSTOMER1 = null;
            this.PROMOTION1 = null;
        }
    
        public int id { get; set; }
        public System.DateTime time { get; set; }
        public string customer { get; set; }
        public Nullable<int> promotion { get; set; }
        public Nullable<int> total { get; set; }
        public string comment { get; set; }
    
        public virtual IList<CART> CARTS { get; set; }
        public virtual CUSTOMER CUSTOMER1 { get; set; }
        public virtual IList<HISTORY> HISTORIES { get; set; }
        public virtual PROMOTION PROMOTION1 { get; set; }

        public override bool Equals(object obj)
        {
            return obj is ORDER o &&
                   id == o.id &&
                   time == o.time &&
                   customer == o.customer &&
                   promotion == o.promotion &&
                   total == o.total &&
                   comment == o.comment &&
                   EqualityComparer<IList<CART>>.Default.Equals(CARTS, o.CARTS) &&
                   EqualityComparer<CUSTOMER>.Default.Equals(CUSTOMER1, o.CUSTOMER1) &&
                   EqualityComparer<IList<HISTORY>>.Default.Equals(HISTORIES, o.HISTORIES) &&
                   EqualityComparer<PROMOTION>.Default.Equals(PROMOTION1, o.PROMOTION1);
        }

        public override int GetHashCode()
        {
            int hashCode = 97684958;
            hashCode = hashCode * -1521134295 + id.GetHashCode();
            hashCode = hashCode * -1521134295 + time.GetHashCode();
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(customer);
            hashCode = hashCode * -1521134295 + promotion.GetHashCode();
            hashCode = hashCode * -1521134295 + total.GetHashCode();
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(comment);
            hashCode = hashCode * -1521134295 + EqualityComparer<IList<CART>>.Default.GetHashCode(CARTS);
            hashCode = hashCode * -1521134295 + EqualityComparer<CUSTOMER>.Default.GetHashCode(CUSTOMER1);
            hashCode = hashCode * -1521134295 + EqualityComparer<IList<HISTORY>>.Default.GetHashCode(HISTORIES);
            hashCode = hashCode * -1521134295 + EqualityComparer<PROMOTION>.Default.GetHashCode(PROMOTION1);
            return hashCode;
        }
    }
}
