//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellProducts.Model
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media.Imaging;

    public partial class PRODUCT
    {
        public PRODUCT()
        {
            this.CARTS = null;
            this.CATEGORIES = null;
            this.MADEIN1 = null;
            this.MANUFACTURERE = null;
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> price_sale { get; set; }
        public string describe { get; set; }
        public string detail { get; set; }
        public Nullable<int> amount_current { get; set; }
        public Nullable<int> madein { get; set; }
        public Nullable<int> manufacturer { get; set; }
        public bool is_hide { get; set; }
    
        public virtual IList<CART> CARTS { get; set; }
        public virtual MADEIN MADEIN1 { get; set; }
        public virtual MANUFACTURER MANUFACTURERE { get; set; }
        public virtual IList<CATEGORY> CATEGORIES { get; set; }
    }
}
