//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellProducts.Model.Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROMOTION
    {
        public PROMOTION()
        {
            this.ORDERS = new HashSet<ORDER>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public string detail { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public string type { get; set; }
        public Nullable<decimal> percent_discount { get; set; }
        public Nullable<int> discount { get; set; }
        public bool is_stop { get; set; }
        public bool is_hide { get; set; }
        public Nullable<int> amount { get; set; }
    
        public virtual ICollection<ORDER> ORDERS { get; set; }
    }
}
