//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellProducts.Model.Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETTING
    {
        public string name { get; set; }
        public string value { get; set; }
        public string account { get; set; }
    
        public virtual MANAGER MANAGER { get; set; }
    }
}
